#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later

. /lib/functions/system.sh
. /lib/functions/uci-defaults.sh

board_config_update

case "$(board_name)" in
	zte,133)
		ucidef_set_interface_lan "eth1 eth2 eth3"
		ucidef_set_interface_wan "eth0"
		;;
esac

board_config_flush

exit 0
